---
- name: set the DNS for the private adapter to point to the DC
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ windows_domain_controller_info.ipv4 }}"

- name: join host to domain
  win_domain_membership:
    dns_domain_name: "{{ windows_domain_controller_info.dns_domain_name }}"
    domain_admin_user: "{{ windows_domain_controller_info.domain_admin_user }}"
    domain_admin_password: "{{ windows_domain_controller_info.domain_admin_password }}"
    state: domain
  register: pri_domain_join_result

- name: reboot host to finalise domain join
  win_reboot:
  when: pri_domain_join_result.reboot_required

- name: test out domain user logon
  win_whoami:
  become: true
  become_method: runas
  vars:
    ansible_become_user: "{{ windows_domain_controller_info.domain_admin_user }}"
    ansible_become_password: "{{ windows_domain_controller_info.domain_admin_password }}"
