---
- name: assert the mandatory variables have been set
  assert:
    that:
    - man_domain_join_domain_name is defined
    - man_domain_join_username is defined
    - man_domain_join_password is defined

- name: set the DNS for the private adapter to point to the DC
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ windows_domain_controller_info.ipv4 }}"

- name: join host to domain
  win_domain_membership:
    dns_domain_name: '{{ man_domain_join_domain_name }}'
    domain_admin_user: '{{ man_domain_join_username }}'
    domain_admin_password: '{{ man_domain_join_password }}'
    state: domain
  register: pri_domain_join_result

- name: reboot host to finalise domain join
  win_reboot:
  when: pri_domain_join_result.reboot_required

- name: test out domain user logon
  win_whoami:
  become: true
  become_method: runas
  vars:
    ansible_become_user: '{{ man_domain_join_username }}'
    ansible_become_password: '{{ man_domain_join_password }}'
