---

- name: Create domain Users
  win_domain_user:
    name: '{{ user }}'
    upn: '{{ user }}@{{ windows_domain_controller_info.domain_name }}'
    description: '{{ user }} Domain User'
    password: '{{ windows_domain_controller_info.domain_users_password }}'
    password_never_expires: yes
    groups: '{{ windows_domain_controller_info.domain_users_default_groups }}'
    state: present
  loop: "{{ windows_domain_controller_info.domain_users }}"
  loop_control:
    loop_var: user