memory = 4096
cpus = 2

Vagrant.configure("2") do |config|
  config.vm.define "cl" do |config|
    config.vm.box = "jborean93/WindowsServer2022"
    config.vm.hostname = "windows-2022-cl"
    config.vm.network :private_network, ip: "192.168.56.107", gateway: "192.168.56.1"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/playbooks/client.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provider :libvirt do |v|
      v.memory = memory
      v.cpus = cpus
    end

    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "windows-2019-cl"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", memory]
      vb.customize ["modifyvm", :id, "--cpus", cpus]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
