# Ansible Settings
ansible_connection: psrp
ansible_psrp_auth: basic
ansible_psrp_cert_validation: ignore

# Domain Controller
windows_domain_controller_info:
  ipv4: 192.168.121.121
  state: domain_controller
  dns_domain_name: c4bag.local
  safe_mode_password: a31557c9-4d4f
  domain_admin_password: a31557c9-4d4f
  domain_admin_user: administrator@c4bag.local
  domain_users:
    - name: saerge
      password: ergDnerogh663!$$99eegeQ
    - name: tzktzzutzut
      password: tzktzzuGtzutrogh663!$$99eegeDF
    - name: erzrtjrghmgg
      password: erzrtjDrghmggh663!$$99eegeS
    - name: zukjrthhll
      password: ergne5S68zukj$!rthhll99eegeV
    - name: oopsoerge
      password: ergn!ooGpsoerge!$$9eeLLW

# Exchange Server
microsoft_exchange_server_info:
  version: 2019
  iso: /home/bjoernbrauel/Workspace/linux/ansible-exchange-dc/iso/ExchangeServer2019-x64-CU12.ISO
