# Ansible Settings
ansible_connection: psrp
ansible_psrp_auth: basic
ansible_psrp_cert_validation: ignore

# Domain Controller
windows_domain_controller_info:
  ipv4: 192.168.121.68

  safe_mode_password: a31557c9-4d4f

  domain_name: c4bag.local
  domain_admin_password: a31557c9-4d4f
  domain_admin_user: administrator@c4bag.local

  # Groups assigned to all domain_users
  domain_users_default_groups:
    - Domain Users
    - Remote Desktop Users
    - Remote Management Users
  
  # Password for domain users
  domain_users_password: 4rr89Ts1-889a
  
  # Domain users to create
  domain_users:
    - saerge
    - tzktzzutzut
    - erzrtjrghmgg
    - zukjrthhll
    - oopsoerge

# Exchange Server
microsoft_exchange_server_info:
  version: 2019
  iso: /home/bjoernbrauel/Workspace/linux/ansible-exchange-dc/iso/ExchangeServer2019-x64-CU12.ISO
