- hosts: cl
  gather_facts: True

  vars_files:
    - ../vars/vars.yml

  roles:
    - name: common

    - name: domain-join

    - name: adcs-winrm
      vars:
        winrm_is_dc: false

    - name: office365
