- hosts: dc
  gather_facts: True

  vars_files:
    - ../vars/vars.yml

  roles:
    - name: common

    - name: windows_dns_server

    - name: windows_domain_controller

    - name: adcs-enrollment

    - name: adcs-winrm
      vars:
        winrm_is_dc: true

  post_tasks:
    - name: Store certificate chain PEM
      vars:
        ansible_connection: local
      copy:
        content: "{{ out_adcs_enrollment_chain_thumbprint }}"
        dest: ../../certs/ca_chain.pem
      delegate_to: localhost
