Vagrant.configure("2") do |config|
  config.vm.define "dc" do |config|
    config.vm.box = "jborean93/WindowsServer2022"
    config.vm.hostname = "windows-2022-dc"
    config.vm.network :public_network, ip: "192.168.56.105", gateway: "192.168.56.1"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/playbooks/dc.yml"
        ansible.config_file = "../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "windows-2022-dc"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
